# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Run 'LogoGenerator' tool from REDUCE Suite
#' 
#' @param argv A commandline option string
#' @return An optional error code
#' @export
LogoGenerator <- function(arguments) {
    invisible(.Call('_NRLBtools_LogoGenerator', PACKAGE = 'NRLBtools', arguments))
}

#' Multiply a number by two
#' 
#' @param x A single integer
#' @return An integer
#' @export
timesTwo <- function(x) {
    .Call('_NRLBtools_timesTwo', PACKAGE = 'NRLBtools', x)
}

