# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.LogoGenerator <- function(argstr) {
    invisible(.Call('_NRLBtools_LogoGenerator_cmdline', PACKAGE = 'NRLBtools', argstr))
}

LogoGenerator_Cpp <- function(output, file, logo, title, ymin, ymax) {
    invisible(.Call('_NRLBtools_LogoGenerator_Cpp', PACKAGE = 'NRLBtools', output, file, logo, title, ymin, ymax))
}

