# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Run 'LogoGenerator' tool from REDUCE Suite
#' 
#' @param argstr Commandline argument string
#' @return None [return path to logo file in future?]
#' @export
LogoGenerator_cmdline <- function(argstr) {
    invisible(.Call('_NRLBtools_LogoGenerator_cmdline', PACKAGE = 'NRLBtools', argstr))
}

LogoGenerator_Cpp <- function(output, file, logo, title, ymin, ymax) {
    invisible(.Call('_NRLBtools_LogoGenerator_Cpp', PACKAGE = 'NRLBtools', output, file, logo, title, ymin, ymax))
}

#' Run 'LogoGenerator' tool from REDUCE Suite
#' 
#' @param argv A commandline option string
#' @return An optional error code
#' @export
TestParseCommandLine <- function(commandline) {
    invisible(.Call('_NRLBtools_TestParseCommandLine', PACKAGE = 'NRLBtools', commandline))
}

#' Run 'LogoGenerator' tool from REDUCE Suite
#' 
#' @param argv A commandline option string
#' @return An optional error code
#' @export
TestParseStringVectorArgs <- function(arguments) {
    invisible(.Call('_NRLBtools_TestParseStringVectorArgs', PACKAGE = 'NRLBtools', arguments))
}

#' Multiply a number by two
#' 
#' @param x A single integer
#' @return An integer
#' @export
timesTwo <- function(x) {
    .Call('_NRLBtools_timesTwo', PACKAGE = 'NRLBtools', x)
}

